export const StateNames = {
    IN: "India",
    ap: "Andhra Pradesh",
    ar: "Arunachal Pradesh",
    as: "Assam",
    br: "Bihar",
    ct: "Chhattisgarh",
    ga: "Goa",
    gj: "Gujarat",
    hr: "Haryana",
    hp: "Himachal Pradesh",
    jh: "Jharkhand",
    ka: "Karnataka",
    kl: "Kerala",
    mp: "Madhya Pradesh",
    mh: "Maharashtra",
    mn: "Manipur",
    ml: "Meghalaya",
    mz: "Mizoram",
    nl: "Nagaland",
    or: "Odisha",
    pb: "Punjab",
    rj: "Rajasthan",
    sk: "Sikkim",
    tn: "Tamil Nadu",
    tg: "Telangana",
    tr: "Tripura",
    up: "Uttar Pradesh",
    ut: "Uttarakhand",
    wb: "West Bengal",
    an: "Andaman and Nicobar Islands",
    ch: "Chandigarh",
    dn: "Dadra and Nagar Haveli and Daman and Diu",
    dl: "Delhi",
    jk: "Jammu and Kashmir",
    la: "Ladakh",
    ld: "Lakshadweep",
    py: "Puducherry"
}